FROM postgres:15

# Copy PostgreSQL schema file
COPY db/schema_postgresql.sql /docker-entrypoint-initdb.d/

# Set environment variables
ENV POSTGRES_DB=nyc_taxi
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

# Expose port
EXPOSE 5432
